degree_sampling: ''
density: 0.6
field: GF31
gb_type: cauchy
max_degree_F: 3
max_degree_G: 5
max_num_terms_F: 2
max_num_terms_G: 5
max_size_F: 5
num_duplicants: 1
num_samples_test: 1000
num_samples_train: 1000
num_var: 3
term_sampling: uniform
