coeff_bound: 100
degree_sampling: ''
density: 1.0
field: RR
gb_type: shape
max_coeff_F: 5
max_coeff_G: 5
max_degree_F: 3
max_degree_G: 5
max_num_terms_F: 2
max_num_terms_G: 5
max_size_F: 4
num_bound_F: 5
num_bound_G: 5
num_duplicants: 1
num_samples_test: 1000
num_samples_train: 1000
num_var: 2
term_sampling: uniform
